# Generated by Django 3.0.5 on 2020-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('product_type', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'COFFEE MACHINE LARGE'), ('COFFEE_MACHINE_SMALL', 'COFFEE MACHINE SMALL'), ('ESPRESSO_MACHINE', 'ESPRESSO MACHINE')], max_length=100)),
                ('model_type', models.CharField(choices=[('base_model', 'Base Model'), ('premium_model', 'Premium Model'), ('deluxe_model', 'Deluxe Model')], max_length=100)),
                ('water_line_compatible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('product_type', models.CharField(choices=[('COFFEE_POD_LARGE', 'COFFEE POD LARGE'), ('COFFEE_POD_SMALL', 'COFFEE POD SMALL'), ('ESPRESSO_POD', 'ESPRESSO POD')], max_length=100)),
                ('coffee_flavor', models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'VANILLA'), ('COFFEE_FLAVOR_CARAMEL', 'CARAMEL'), ('COFFEE_FLAVOR_PSL', 'PSL'), ('COFFEE_FLAVOR_MOCHA', 'MOCHA'), ('COFFEE_FLAVOR_HAZELNUT', 'HAZELNUT')], max_length=100)),
                ('pack_size', models.PositiveIntegerField(choices=[(12, '1 dozen'), (36, '3 dozen'), (60, '5 dozen'), (84, '7 dozen')], max_length=100)),
            ],
        ),
    ]
